# patient_cart.classic.controllers.yaml

controller_manager:
    ros__parameters:
        use_sim_time: true
        update_rate: 100

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        forward_position_controller:
            type: position_controllers/JointGroupPositionController

forward_position_controller:
    ros__parameters:
        joints:
            - ECM_yaw
            - ECM_pitch
            - ECM_insertion
            - ECM_roll
            - SUJ_ECM_J0
            - SUJ_ECM_J1
            - SUJ_ECM_J2
            - SUJ_ECM_J3
            - SUJ_PSM1_J0
            - SUJ_PSM1_J1
            - SUJ_PSM1_J2
            - SUJ_PSM1_J3
            - SUJ_PSM1_J4
            - SUJ_PSM2_J0
            - SUJ_PSM2_J1
            - SUJ_PSM2_J2
            - SUJ_PSM2_J3
            - SUJ_PSM2_J4
            - SUJ_PSM3_J0
            - SUJ_PSM3_J1
            - SUJ_PSM3_J2
            - SUJ_PSM3_J3
            - SUJ_PSM3_J4
            - PSM1_outer_yaw
            - PSM1_pitch
            - PSM1_outer_insertion
            - PSM1_outer_roll
            - PSM1_outer_wrist_pitch
            - PSM1_outer_wrist_yaw
            - PSM1_jaw
            - PSM2_outer_yaw
            - PSM2_pitch
            - PSM2_outer_insertion
            - PSM2_outer_roll
            - PSM2_outer_wrist_pitch
            - PSM2_outer_wrist_yaw
            - PSM2_jaw
            - PSM3_outer_yaw
            - PSM3_pitch
            - PSM3_outer_insertion
            - PSM3_outer_roll
            - PSM3_outer_wrist_pitch
            - PSM3_outer_wrist_yaw
            - PSM3_jaw
        interface_name: position
